//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEMA
{
    using System;
    using System.Collections.Generic;
    
    public partial class historico
    {
        public int id { get; set; }
        public string mensagem { get; set; }
        public Nullable<int> chamadoID { get; set; }
        public Nullable<int> sequencia { get; set; }
        public Nullable<System.DateTime> data { get; set; }
    
        public virtual chamado chamado { get; set; }
    }
}
