//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEMA
{
    using System;
    using System.Collections.Generic;
    
    public partial class secretaria
    {
        public secretaria()
        {
            this.configuracoes = new HashSet<configuraco>();
            this.usuarios = new HashSet<usuario>();
            this.chamadoes = new HashSet<chamado>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
    
        public virtual ICollection<configuraco> configuracoes { get; set; }
        public virtual ICollection<usuario> usuarios { get; set; }
        public virtual ICollection<chamado> chamadoes { get; set; }
    }
}
