//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEMA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class semaEntities : DbContext
    {
        public semaEntities()
            : base("name=semaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<assunto> assuntoes { get; set; }
        public DbSet<chamado> chamadoes { get; set; }
        public DbSet<configuraco> configuracoes { get; set; }
        public DbSet<historico> historicoes { get; set; }
        public DbSet<secretaria> secretarias { get; set; }
        public DbSet<topico> topicos { get; set; }
        public DbSet<usuario> usuarios { get; set; }
    }
}
